export const ADD_CHARACTER = "ADD_CHARACTER";
export const UPDATE_CHARACTER_NAME = "UPDATE_CHARACTER_NAME";
export const UPDATE_CHARACTER_LEVEL = "UPDATE_CHARACTER_LEVEL";
export const UPDATE_CHARACTER_GEAR_LEVEL = "UPDATE_CHARACTER_GEAR_LEVEL";

export const SET_MY_ROSTER = "SET_MY_ROSTER";
export const SET_MY_INVENTORY = "SET_MY_INVENTORY";
export const UPDATE_GEAR_NEEDED = "UPDATE_GEAR_NEEDED";
export const UPDATE_GEAR_NEEDED_V2 = "UPDATE_GEAR_NEEDED_V2";
export const UPDATE_GEAR_DIFFERENCE = "UPDATE_GEAR_DIFFERENCE";
export const UPDATE_GEAR_DIFFERENCE_V2 = "UPDATE_GEAR_DIFFERENCE_V2";
